version: '{build}'
shallow_clone: true
build: off

image:
  - Visual Studio 2017

environment:
  matrix:
#    - perl_type: strawberry
#      perl_version: 5.30.1.1
#      perl_bits: 32
#      #gcc 8.3.0
#    - perl_type: strawberry
#      perl_version: 5.30.1.1
#      perl_bits: 64
#      #gcc 8.3.0
#    - perl_type: strawberry
#      perl_version: 5.28.2.1
#      perl_bits: 32
#      #gcc 7.1.0
#    - perl_type: strawberry
#      perl_version: 5.28.2.1
#      perl_bits: 64
#      #gcc 7.1.0
#    - perl_type: strawberry
#      perl_version: 5.26.3.1
#      perl_bits: 32
#      #gcc 7.1.0
#    - perl_type: strawberry
#      perl_version: 5.26.3.1
#      perl_bits: 64
#      #gcc 7.1.0
#    - perl_type: strawberry
#      perl_version: 5.24.4.1
#      perl_bits: 32
#      #gcc 4.9.2
#    - perl_type: strawberry
#      perl_version: 5.24.4.1
#      perl_bits: 64
#      #gcc 4.9.2
#    - perl_type: strawberry
#      perl_version: 5.22.3.1
#      perl_bits: 32
#      #gcc 4.9.2
#    - perl_type: strawberry
#      perl_version: 5.22.3.1
#      perl_bits: 64
#      #gcc 4.9.2
#    - perl_type: strawberry
#      perl_version: 5.20.3.3
#      perl_bits: 32
#      #gcc 4.8.3
#    - perl_type: strawberry
#      perl_version: 5.20.3.3
#      perl_bits: 64
#      #gcc 4.8.3
#    - perl_type: strawberry
#      perl_version: 5.18.4.1
#      perl_bits: 32
#      #gcc 4.7.3
#    - perl_type: strawberry
#      perl_version: 5.18.4.1
#      perl_bits: 64
#      #gcc 4.7.3
#    - perl_type: strawberry
#      perl_version: 5.16.3.1
#      perl_bits: 32
#      #gcc 4.6.3
#    - perl_type: strawberry
#      perl_version: 5.16.3.1
#      perl_bits: 64
#      #gcc 4.6.3
#    - perl_type: strawberry
#      perl_version: 5.14.4.1
#      perl_bits: 32
#      #gcc 4.6.3
#    - perl_type: strawberry
#      perl_version: 5.14.4.1
#      perl_bits: 64
#      #gcc 4.6.3
    - perl_type: strawberry_old
      perl_version: 5.12.3.0
      #gcc ??
    - perl_type: strawberry_old
      perl_version: 5.10.1.2
      #gcc 3.4.5
    - perl_type: cygwin32
    - perl_type: cygwin64

init:
  - reg add "HKLM\SYSTEM\CurrentControlSet\Control\Windows" /f /v ErrorMode /d 2
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1  

install:
  - 'call .appveyor.cmd perl_setup'
  - 'perl -V'
  - 'gcc -v'
  - '%cpanm% --notest Cpanel::JSON::XS Math::BigInt Test::Pod Pod::Coverage'
  - '%cpanm% --notest --installdeps --with-recommends .'

build_script:
  - 'perl Makefile.PL'
  - '%make%'

test_script:
  - '%make% test'
