language: perl
matrix:
  include:
  - perl: "5.22"
  - perl: "5.24"
  - perl: "5.26"
  - perl: "5.28"
  - perl: "5.30"
  allow_failures:
  - perl: blead
env:
  global:
    - HARNESS_OPTIONS=j4
    - MAKEFLAGS=-j4
    - AUTHOR_MODE=1
install:
  - cpanm -n Cpanel::JSON::XS Math::BigInt Test::Pod Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
