name: 02-bsd-tests

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  BSDs:
    runs-on: macos-latest
  
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '12.4'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker p5-JSON
          - name: freebsd
            version: '13.2'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker p5-JSON
          - name: openbsd
            version: '6.9'
            pkginstall: pkg_add p5-ExtUtils-MakeMaker p5-JSON
          - name: openbsd
            version: '7.3'
            pkginstall: pkg_add p5-ExtUtils-MakeMaker p5-JSON
          - name: netbsd
            version: '9.3'
            pkginstall: pkg_add p5-ExtUtils-MakeMaker p5-JSON

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Build+Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            curl -L https://cpanmin.us | sudo perl - --verbose --notest --installdeps --with-configure --with-develop .
            sudo make realclean
            perl Makefile.PL
            make -j4
            prove -b t
