name: 02-linux-x64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  linux-gcc10:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bullseye
        perl-version:
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}-${{ matrix.codename }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
      - name: Run build
        run: |
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 1
      - name: Run tests
        run: prove -b t
        env:
          AUTHOR_MODE: 1

  linux-gcc8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename:
          - buster
        perl-version:
          - '5.8'
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - '5.36'
          - '5.38'
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}-${{ matrix.codename }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
      - name: Run build
        run: |
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 1
      - name: Run tests
        run: prove -b t
        env:
          AUTHOR_MODE: 1
