name: 03-linux-i386

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  linux-i386:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bullseye
          - bookworm
    container:
      image: i386/perl:5.40-${{ matrix.codename }}
    steps:
      - name: Checkout code using git
        run: |
          git clone --single-branch --branch $(echo ${GITHUB_REF#refs/heads/}) https://github.com/${{ github.repository }}.git
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Run build
        run: |
          cd $(basename ${{ github.repository }})
          cpanm -n --installdeps .
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 1
      - name: Run tests
        run: |
          cd $(basename ${{ github.repository }})
          prove -b t
        env:
          AUTHOR_MODE: 1
