name: 05-debian

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  debian-current:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        codename:
          - forky
          - trixie
          - bookworm
    container:
      image: debian:${{ matrix.codename }}
    steps:
      - name: Show OS release
        run: cat /etc/os-release || cat /etc/debian_version || echo unknown-release
      - name: Install dependencies
        run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends \
            ca-certificates \
            gcc \
            git \
            libc6-dev \
            libcrypt-dev \
            libmath-bigint-perl \
            libjson-perl \
            make \
            perl
      - name: Checkout code using git
        run: |
          git clone --branch $(echo ${GITHUB_REF#refs/heads/}) https://github.com/${{ github.repository }}.git
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Run build
        run: |
          cd $(basename ${{ github.repository }})
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 0
      - name: Run tests
        run: |
          cd $(basename ${{ github.repository }})
          prove -j 4 -b t
        env:
          AUTHOR_MODE: 0

  debian-eol:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bullseye
          - buster
          - stretch
          - jessie
          - wheezy
    container:
      image: debian/eol:${{ matrix.codename }}
    steps:
      - name: Show OS release
        run: cat /etc/os-release || cat /etc/debian_version || echo unknown-release
      - name: Install dependencies
        run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends \
            ca-certificates \
            gcc \
            git \
            libc6-dev \
            libmath-bigint-perl \
            libjson-perl \
            make \
            perl
      - name: Checkout code using git
        run: |
          git clone --branch $(echo ${GITHUB_REF#refs/heads/}) https://github.com/${{ github.repository }}.git
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Run build
        run: |
          cd $(basename ${{ github.repository }})
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 0
      - name: Run tests
        run: |
          cd $(basename ${{ github.repository }})
          prove -j 4 -b t
        env:
          AUTHOR_MODE: 0
