name: 07-freebsd-arm64

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  freebsd-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run on FreeBSD arm64
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          arch: "aarch64"
          usesh: true
          run: |
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            git clone --single-branch --branch "$(echo ${GITHUB_REF#refs/heads/})" https://github.com/${GITHUB_REPOSITORY}.git
            perl -V
            gcc -v
            cd "$(basename "${GITHUB_REPOSITORY}")"
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t
