name: 07-freebsd-arm64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  freebsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on FreeBSD x86_64
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            gcc -v
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  freebsd-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on FreeBSD aarch64
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          arch: "aarch64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            gcc -v
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  freebsd-riscv64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on FreeBSD riscv64
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: "riscv64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            export ASSUME_ALWAYS_YES=yes
            pkg -N >/dev/null 2>&1 || pkg bootstrap -f
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            pkg --version || true
            pkg_add --version || true
            perl -V || true
            gcc -v || true
            cc -v || true
            clang -v || true
            curl --version || true
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t

  netbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on NetBSD x86_64
      - uses: actions/checkout@v4
      - uses: vmactions/netbsd-vm@v1
        with:
          release: "10.1"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add pkgin
            pkgin -y update
            pkgin -y install curl perl p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t

  netbsd-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on NetBSD aarch64
      - uses: actions/checkout@v4
      - uses: vmactions/netbsd-vm@v1
        with:
          release: "10.1"
          arch: "aarch64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add pkgin
            pkgin -y update
            pkgin -y install curl perl p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t

  openbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on OpenBSD x86_64
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          release: "7.7"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add curl p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            curl -L https://cpanmin.us/ -o cpanm
            chmod +x cpanm
            ./cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  openbsd-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Run on OpenBSD aarch64
      - uses: actions/checkout@v4
      - uses: vmactions/openbsd-vm@v1
        with:
          release: "7.7"
          arch: "aarch64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add curl p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            curl -L https://cpanmin.us/ -o cpanm
            chmod +x cpanm
            ./cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t
