name: 07-vmactions

#### https://github.com/vmactions
# https://github.com/vmactions/freebsd-vm
# https://github.com/vmactions/haiku-vm
# https://github.com/vmactions/netbsd-vm
# https://github.com/vmactions/openbsd-vm
# https://github.com/vmactions/solaris-vm

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  freebsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            gcc -v
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  freebsd-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          arch: "aarch64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg update
            pkg install -y git gmake gcc perl5 p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            gcc -v
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  netbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/netbsd-vm@v1
        with:
          release: "10.1"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add pkgin
            pkgin -y update
            pkgin -y install curl perl p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t

  netbsd-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/netbsd-vm@v1
        with:
          release: "10.1"
          arch: "aarch64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add pkgin
            pkgin -y update
            pkgin -y install curl perl p5-App-cpanminus p5-Math-BigInt p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j2
            env AUTHOR_MODE=0 prove -b t

  openbsd-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/openbsd-vm@v1
        with:
          release: "7.7"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkg_add curl p5-JSON
            perl -V
            egcc -v || gcc -v || cc -v || echo unknown-cc
            curl -L https://cpanmin.us/ -o cpanm
            chmod +x cpanm
            ./cpanm -n --installdeps .
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  openbsd-aarch64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        relver:
          - 7.4
          - 7.6
          - 7.8
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/openbsd-vm@v1
        with:
          release: "${{matrix.relver}}"
          arch: aarch64
          usesh: true
          sync: scp
          copyback: false
          prepare: |
            set -eu
            pkg_add curl
            curl -L https://cpanmin.us/ -o cpanm
            chmod +x cpanm
            ./cpanm -n --installdeps .
            ./cpanm -n JSON
      - name: Info
        run: |
          set -eu
          uname -a
          cc -v || true
          gcc -v || true
          egcc -v || true
          clang -v || true
          perl -V
      - name: Build
        run: |
          set -eu
          env AUTHOR_MODE=0 perl Makefile.PL
          make -j3
      - name: Test
        run: |
          set -eu
          env AUTHOR_MODE=0 prove -j3 -b t

  haiku-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/haiku-vm@v1
        with:
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a
            pkgman refresh
            pkgman install -y git make gcc perl
            perl -V
            gcc -v
            if ! command -v cpanm >/dev/null 2>&1; then
              curl -L https://cpanmin.us | perl - App::cpanminus
              export PATH="$HOME/perl5/bin:$PATH"
            fi
            cpanm -n --installdeps .
            cpanm JSON
            env AUTHOR_MODE=0 perl Makefile.PL
            make -j4
            env AUTHOR_MODE=0 prove -b t

  solaris-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/solaris-vm@v1
        with:
          release: "11.4-gcc"
          arch: "x86_64"
          usesh: true
          sync: scp
          copyback: false
          run: |
            uname -a

            pkg refresh
            pkg install --accept \
              developer/gcc \
              developer/build/gnu-make \
              developer/versioning/git \
              runtime/perl-532
            export PATH="/usr/gnu/bin:/usr/gcc/bin:/usr/perl5/bin:$PATH"
            perl -V
            gcc -v

            if ! command -v cpanm >/dev/null 2>&1; then
              curl -L https://cpanmin.us | perl - App::cpanminus
              export PATH="$HOME/perl5/bin:$PATH"
            fi
            cpanm -n --installdeps .
            cpanm JSON

            env AUTHOR_MODE=0 perl Makefile.PL
            gmake -j4
            env AUTHOR_MODE=0 prove -b t
